# Generated by Django 2.1.5 on 2019-01-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('pos_code', models.CharField(blank=True, max_length=100)),
                ('phone_code', models.IntegerField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('fax_code', models.IntegerField(blank=True)),
                ('fax', models.IntegerField(blank=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=100)),
                ('pic_name', models.CharField(blank=True, max_length=100)),
                ('pic_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'MasterCustomer',
            },
        ),
        migrations.CreateModel(
            name='master_group_item',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MasterGroupItem',
            },
        ),
        migrations.CreateModel(
            name='master_item',
            fields=[
                ('master_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('alias_name', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=200)),
                ('price2', models.CharField(blank=True, max_length=200)),
                ('price3', models.CharField(blank=True, max_length=200)),
                ('master_group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_group_item')),
            ],
            options={
                'db_table': 'MasterItem',
            },
        ),
        migrations.CreateModel(
            name='master_location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'MasterLokasi',
            },
        ),
        migrations.CreateModel(
            name='master_merk',
            fields=[
                ('merk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MasterMerk',
            },
        ),
        migrations.CreateModel(
            name='master_uom',
            fields=[
                ('uom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MasterUOM',
            },
        ),
        migrations.CreateModel(
            name='master_user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('user_level', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('last_login_date', models.DateField()),
            ],
            options={
                'db_table': 'MasterUser',
            },
        ),
        migrations.CreateModel(
            name='master_vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'MasterVendor',
            },
        ),
        migrations.CreateModel(
            name='receiving_detail',
            fields=[
                ('receiving_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('master_item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_item')),
            ],
            options={
                'db_table': 'ReceivingDetail',
            },
        ),
        migrations.CreateModel(
            name='receiving_header',
            fields=[
                ('receiving_header_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=100)),
                ('number_preix', models.CharField(max_length=100)),
                ('counter', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('approval1_date', models.DateField(blank=True, null=True)),
                ('approval1', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_user')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_vendor')),
            ],
            options={
                'db_table': 'ReceivingHeader',
            },
        ),
        migrations.AddField(
            model_name='receiving_detail',
            name='receiving_header_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.receiving_header'),
        ),
        migrations.AddField(
            model_name='receiving_detail',
            name='uom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_uom'),
        ),
        migrations.AddField(
            model_name='master_item',
            name='merk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_merk'),
        ),
        migrations.AddField(
            model_name='master_item',
            name='uom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_uom'),
        ),
    ]
