# Generated by Django 2.1.1 on 2018-11-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_barang',
            name='merk',
        ),
        migrations.AddField(
            model_name='master_barang',
            name='merk',
            field=models.ManyToManyField(to='api.master_merk'),
        ),
    ]
