# Generated by Django 2.1.1 on 2020-01-21 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_akses', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_detail',
            fields=[
                ('invoice_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('type_payment', models.CharField(blank=True, max_length=50)),
                ('pay_amount', models.BigIntegerField(blank=True)),
                ('pay_method', models.CharField(blank=True, max_length=50)),
                ('noted', models.TextField(blank=True)),
                ('jml_period', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('harga_rental', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'InvoiceDetail',
            },
        ),
        migrations.CreateModel(
            name='invoice_header',
            fields=[
                ('invoice_header_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('customer', models.BigIntegerField(blank=True)),
                ('pay_method', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'InvoiceHeader',
            },
        ),
        migrations.CreateModel(
            name='rental_detail_sn',
            fields=[
                ('rental_detail_sn_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='rental_detail',
            old_name='discount_value',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='stock_sn_history',
            old_name='ref_id',
            new_name='IncomingRef_id',
        ),
        migrations.RemoveField(
            model_name='master_user',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='master_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='master_user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='master_user',
            name='username',
        ),
        migrations.AddField(
            model_name='master_item',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_user',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master_user',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental_detail',
            name='discount_method',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rental_stock_sn',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stock_sn_history',
            name='RentalRef_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RentalHeader', to='api.rental_header'),
        ),
        migrations.AlterField(
            model_name='master_customer',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='master_employee',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_group_item',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_group_item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_item',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='master_item',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='master_location',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_location',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='master_merk',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_uom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='master_user',
            name='employee_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_employee'),
        ),
        migrations.AlterField(
            model_name='master_vendor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='receiving_detail_sn',
            name='receiving_detail_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='RDISN', to='api.receiving_detail'),
        ),
        migrations.AlterField(
            model_name='receiving_header',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiving_header',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='receiving_header',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receiving_header',
            name='number_preix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receiving_header',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='total',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='counter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_customer'),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_location'),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental_header',
            name='number_prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental_order_detail',
            name='discount_method',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental_order_detail',
            name='discount_type',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental_order_header',
            name='counter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental_order_header',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_customer'),
        ),
        migrations.AlterField(
            model_name='rental_order_header',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental_order_header',
            name='number_prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_sn_history',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental_detail_sn',
            name='rental_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RDSN', to='api.rental_detail'),
        ),
        migrations.AddField(
            model_name='rental_detail_sn',
            name='stock_code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.rental_stock_sn'),
        ),
        migrations.AddField(
            model_name='invoice_header',
            name='rental_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.rental_header'),
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='invoice_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='InvoiceDetails', to='api.invoice_header'),
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='master_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Items', to='api.master_item'),
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_user'),
        ),
    ]
