# Generated by Django 2.1.5 on 2019-02-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190207_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiving_detail_sn',
            fields=[
                ('receiving_detail_sn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_serial_number', models.CharField(blank=True, max_length=100)),
                ('new_serial_number', models.CharField(blank=True, max_length=100)),
                ('receiving_detail_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.receiving_detail')),
            ],
            options={
                'db_table': 'ReceivingDetailSN',
            },
        ),
    ]
