# Generated by Django 2.1.1 on 2018-11-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181128_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='inven_detail',
            fields=[
                ('id_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('cat_bar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='inven_header',
            fields=[
                ('id_ie', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('cat_doc', models.CharField(max_length=1000)),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='inven_sn',
            fields=[
                ('id_sn', models.AutoField(primary_key=True, serialize=False)),
                ('sn_asli', models.CharField(max_length=100)),
                ('sn_baru', models.CharField(max_length=100)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inven_detail')),
            ],
        ),
        migrations.AddField(
            model_name='inven_detail',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inven_header'),
        ),
        migrations.AddField(
            model_name='inven_detail',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_kategori'),
        ),
        migrations.AddField(
            model_name='inven_detail',
            name='satuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_unit'),
        ),
    ]
