# Generated by Django 2.1.1 on 2018-12-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181128_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inven_detail',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inven_header'),
        ),
        migrations.AlterField(
            model_name='inven_sn',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inven_detail'),
        ),
    ]
