# Generated by Django 2.1.5 on 2019-02-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_receiving_detail_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_order_detail',
            fields=[
                ('order_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('discount_type', models.IntegerField(blank=True, null=True)),
                ('discount_method', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('master_item_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_item')),
            ],
            options={
                'db_table': 'RentalOrderDetail',
            },
        ),
        migrations.CreateModel(
            name='rental_order_header',
            fields=[
                ('sales_order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=100)),
                ('number_prefix', models.CharField(max_length=100)),
                ('counter', models.IntegerField()),
                ('tax', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=100)),
                ('delivery_fee', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('notes_kwitansi', models.CharField(max_length=300)),
                ('salesman', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_customer')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_location')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.master_user')),
            ],
            options={
                'db_table': 'RentalOrderHeader',
            },
        ),
        migrations.AddField(
            model_name='rental_order_detail',
            name='sales_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rental_order_header'),
        ),
    ]
