# Generated by Django 2.1.1 on 2018-12-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181201_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inven_detail',
            name='header',
        ),
    ]
