# Generated by Django 2.1.1 on 2018-12-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_inven_detail_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='inven_detail',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inven_detail',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_kategori'),
        ),
        migrations.AddField(
            model_name='inven_detail',
            name='satuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_unit'),
        ),
    ]
