# Generated by Django 2.1.1 on 2018-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181201_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='inven_detail',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
