# Generated by Django 2.1.1 on 2018-12-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_inven_detail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inven_detail',
            name='nama_barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.master_barang'),
        ),
    ]
